### ISSUE TITLE
include docs about using tilt set to override default values

### ISSUE THREAD

**Issue by rands0n** [tilt-dev/tilt.build#1082]
Recently, I was using the option set to override default values from a helm chart. I know there are other options of how to use this. But didn't found any information related to `set` on the docs.

```
k8s_yaml(helm('./chart', name='tilt-workshop-app', namespace='default', set=['replicaCount=2']))
```

So, I looked at this repository to include this info but didn't found how to do it. There is some place where I can found info on how to include that or some page showing us how to contribute?

I believe this information is valuable and we should have it on the docs page.

What do you guys think?

**Comment by landism** [comment]
Thanks for letting us know!

IIUC, the info you're describing is documented [here](https://docs.tilt.dev/api.html#api.helm) and lives in github [here](https://github.com/tilt-dev/tilt/blob/e9fd74463ca4a833688b4933db0fd8137c40e674/internal/tiltfile/api/__init__.py#L723)

Just to make sure I understand: is the issue that you couldn't find the api docs for `helm`, or that you found it but found its description of `set` lacking?

**Comment by rands0n** [comment]
I found it, but didn't found about the `set`. 

Thanks for the response @landism, closing this issue since we already have it  🤟🏽
