### ISSUE TITLE
config.define_bool code example is jumbled

### ISSUE THREAD

**Issue by jazzdan** [tilt-dev/tilt.build#1096]
See [here](https://docs.tilt.dev/api.html#api.config.define_bool):
<img width="1006" alt="Screen Shot 2022-04-28 at 12 08 51 PM" src="https://user-images.githubusercontent.com/452453/165828091-83008fde-7b90-447e-8b82-ac55e9468f4f.png">

I think that code block is missing some new lines or something?

**Comment by nicks** [comment]
should be fixed in the next tilt release (which updates the api docs)

**Comment by jazzdan** [comment]
Thanks @nicks!
