### ISSUE TITLE
"image" should be replaced with "build" in Docker Compose caveat

### ISSUE THREAD

**Issue by meshulam** [tilt-dev/tilt.build#1106]
#987 added a helpful note for using docker_build() with docker-compose, but it has a small mistake:

> When using Docker Compose, Tilt expects the image build to be either managed by your Docker Compose file (via the `image` key) OR by Tilt's :meth:`docker_build`, but not both.

should be:

> When using Docker Compose, Tilt expects the image build to be either managed by your Docker Compose file (via the `build` key) OR by Tilt's :meth:`docker_build`, but not both.

The inline link points to the right section of the docker-compose docs so I think this was just an oversight. I was about to PR this myself but it seems a little involved to generate the HTML docs, so figured I'd at least open an issue while it's on my mind. Thanks!

**Comment by lizzthabet** [comment]
thanks, @meshulam! (our docs workflow has changed a bit since #987, so i've made that change where the docs source files live now.)
