### ISSUE TITLE
Docs for Tiltfile helpful workarounds/functions

### ISSUE THREAD

**Issue by jazzdan** [tilt-dev/tilt.build#179]
We should describe useful tips and tricks, like how to use str on the blob created by local and how to die on the wrong cluster.

[as mentioned in Kubernetes slack]

[ported from windmilleng/tilt]

**Comment by cyucelen** [comment]
Do you have an answer for how to use str on the blob? My if condition not working because of string to blob comparison.

**Comment by jazzdan** [comment]
Hey @cyucelen,

You should be able to do something like this:

```python
str(local('kubectl config current-context')).rstrip('\n') == 'docker-for-desktop'
```

**Comment by cyucelen** [comment]
It would very helpful to put this kind of recipes to the docs. I can also contribute if you have the place to put it.

**Comment by jazzdan** [comment]
Maybe the answer to this should be [extensions](https://github.com/tilt-dev/tilt-extensions) now that we have them

**Comment by nicks** [comment]
we now have a snippets page for sharing common idioms!
https://docs.tilt.dev/snippets
https://github.com/tilt-dev/tilt.build/blob/master/contributing-snippets.md
