### ISSUE TITLE
Add More Starlark Info to Docs

### ISSUE THREAD

**Issue by jazzdan** [tilt-dev/tilt.build#67]
It's easy to miss the fact that Tiltfiles are written in Starlark. In the guide should we have even just a one paragraph descriptor with some simple examples that demonstrate what Starlark is and how it works?

**Comment by maiamcc** [comment]
It doesn't fully address this issue, but FWIW we now have this:

<img width="1006" alt="Screen Shot 2020-05-07 at 5 03 27 PM" src="https://user-images.githubusercontent.com/6332648/81344399-b087e400-9084-11ea-9758-3b2d9e5367b7.png">
