### ISSUE TITLE
Example version_settings constraints are incorrect

### ISSUE THREAD

**Issue by georgeblahblah** [tilt-dev/tilt.build#767]
The documentation for `version_settings` (https://github.com/tilt-dev/tilt.build/blob/master/api/api.py#L927) specify two examples:

```
- `<0.13.0` - less than 0.13.0
- `>=0.12.0` - at least 0.12.0
```

However, the `constraints` feature was only introduced from version `0.13.2` (I think), so this example would not when running these `tilt` versions.

I propose updating the examples to:

```
- `<0.17.0` - less than 0.17.0
- `>=0.13.2` - at least 0.13.2
```

Although it doesn't quite solve the problem (as `<0.17.0` could still reference a version before `0.13.2`), at least the examples given don't directly state versions where this parameter would not work.

**Comment by nicks** [comment]
thanks for the report! fixed
