### ISSUE TITLE
docs: using multiple repos with tilt

### ISSUE THREAD

**Issue by lianmakesthings** [tilt-dev/tilt.build#989]
Currently, the docs on [Structuring Multiple Repos](https://docs.tilt.dev/multiple_repos.html) is very basic.
It would be good to improve them by e.g. showing an example.

#### How do you deal with merging configs?
- when you load multiple Tiltfiles via `load()` what happens to variables that have been defined in both Tiltfiles?

#### Do you need to wrap top level function calls into a method?

**Comment by nicks** [comment]
this is now updated! https://github.com/tilt-dev/tilt.build/pull/1065
